### ISSUE TITLE
Username, password I set during windows installation is not working.

### ISSUE THREAD

**Issue by amodia** [learningequality/installers#83] opened 2015-07-03 07:36 UTC
**Branch:** 'master'
**Current behavior:** Can't use admin user I set during installation. 
**Expected behavior:** Admin user I set during windows installation must use to log in on kalite.

**Steps to reproduce:**
   1. Install the Build `KaliteSetup.exe`.
   2. During installation set Admin user refer to screenshot below.
   3. Use the Admin user you set during installation to log in on kalite.

![screen shot 2015-07-03 at 1 57 54 pm](https://cloud.githubusercontent.com/assets/8663934/8493568/ab243f46-218e-11e5-8f4e-e88a23b52fff.png)

![screen shot 2015-07-03 at 2 41 05 pm](https://cloud.githubusercontent.com/assets/8663934/8493803/9c934028-2191-11e5-8772-a5e88494c4ea.png)

**Comment by MCGallaspy** [comment] 2015-07-08 17:15
@EdDixon has reported a similar issue. I assume you built the installer yourself @amodia? Which branch of ka-lite did you use? What version of Windows are you using? I haven't seen this issue or been able to reproduce Ed's issue using Windows 8 since #70 was merged, so it would be very helpful to determine how to reproduce this.

**Comment by amodia** [comment] 2015-07-09 13:28
HI @MCGallaspy I can reproduced this issue on dungeon build [#175](http://dungeon.learningequality.org:8085/browse/KL-KALITE014-175/artifact/shared/Windows-Installer/) `KALiteSetup-0.14.0.exe`. And my operating system is `Windows 7 enterprise 32 bit`.

![screen shot 2015-07-09 at 3 56 09 pm](https://cloud.githubusercontent.com/assets/8663934/8596281/aa4277c2-2680-11e5-987f-de624004e9e6.png)
![screen shot 2015-07-09 at 4 17 57 pm](https://cloud.githubusercontent.com/assets/8663934/8596285/b457b420-2680-11e5-9026-6f44b603f124.png)

**Comment by MCGallaspy** [comment] 2015-07-09 17:48
@amodia have you tried this on other versions of Windows? I was unable to reproduce it on Windows 8.

**Comment by amodia** [comment] 2015-07-13 06:00
@MCGallaspy Yeah, it's working on `windows 8.1` I think you can close this issue.

![screen shot 2015-07-13 at 1 49 54 pm](https://cloud.githubusercontent.com/assets/8663934/8643482/05bd75c8-2967-11e5-9ee7-8b473d67295f.png)


![screen shot 2015-07-13 at 1 49 06 pm](https://cloud.githubusercontent.com/assets/8663934/8643437/666ed3ae-2966-11e5-83d7-d2d44589de15.png)

**Comment by MCGallaspy** [comment] 2015-07-13 15:45
Well, I won't close it if it's happening on Windows 7! Let me try it out there.

**Comment by aronasorman** [comment] 2015-10-08 16:28
Stale.

**Closed by aronasorman** 2015-10-08 16:28 UTC
