### ISSUE TITLE
Loading time issue installing on Windows from 0.12.11 to 0.15

### ISSUE THREAD

**Issue by jtamiace** [learningequality/installers#174] opened 2015-09-22 22:44 UTC
@MCGallaspy  Everything works fine installing from 0.12.11 to 0.15, but the time to load the server for the first time took about 10 minutes, but it was considerably shorter the second time around (maybe 2-3 minutes). I guess that's expected though?

All of the video, language, and user data migrated just fine, but there was this one issue when the server started and I first navigated to the video download page. Not sure how much of an issue it is since when I refreshed the page everything displayed ok: 

![0 12 to 0 15 videos](https://cloud.githubusercontent.com/assets/6668144/10033823/a79220a4-6140-11e5-8c3e-8eb6a59cb5e7.PNG)

**Comment by MCGallaspy** [comment] 2015-09-24 17:05
Hard to say about the loading time. It's not _unexpected_, and it might be alleviated if we can address the longstanding issue of there being no visual cues that the server is still starting. Thanks for confirming that everything migrated properly. I'll take a crack at your other error.

**Comment by MCGallaspy** [comment] 2015-09-25 19:54
No issue with video page for me. I expect the load time comes from migrating the DB. Will leave open for now, so we can discuss what if anything we can do to address that.

**Comment by MCGallaspy** [comment] 2015-10-16 21:58
Duplicate of #179

**Closed by MCGallaspy** 2015-10-16 21:58 UTC
Labels: enhancement
