### ISSUE TITLE
PIP Installation method not working on Debian

### ISSUE THREAD

**Issue by EdDixon** [learningequality/installers#232] opened 2015-10-18 14:55 UTC
PIP Installation method failed on Debian but completed succesfully on both Ubuntu 14 LTS and 15.x Below is a trace back and log of the error: 

```

Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-agiU3c/pycrypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-YfY1CT-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-agiU3c/pycrypto
Storing debug log for failure in /root/.pip/pip.log

```

```
running build_ext

running build_configure

checking for gcc... gcc

checking whether the C compiler works... yes

checking for C compiler default output file name... a.out

checking for suffix of executables...

checking whether we are cross compiling... no

checking for suffix of object files... o

checking whether we are using the GNU C compiler... yes

checking whether gcc accepts -g... yes

checking for gcc option to accept ISO C89... none needed

checking for __gmpz_init in -lgmp... no

checking for __gmpz_init in -lmpir... no

checking whether mpz_powm is declared... no

checking whether mpz_powm_sec is declared... no

checking how to run the C preprocessor... gcc -E

checking for grep that handles long lines and -e... /bin/grep

checking for egrep... /bin/grep -E

checking for ANSI C header files... yes

checking for sys/types.h... yes

checking for sys/stat.h... yes

checking for stdlib.h... yes

checking for string.h... yes

checking for memory.h... yes

checking for strings.h... yes

checking for inttypes.h... yes

checking for stdint.h... yes

checking for unistd.h... yes

checking for inttypes.h... (cached) yes

checking limits.h usability... yes

checking limits.h presence... yes

checking for limits.h... yes

checking stddef.h usability... yes

checking stddef.h presence... yes

checking for stddef.h... yes

checking for stdint.h... (cached) yes

checking for stdlib.h... (cached) yes

checking for string.h... (cached) yes

checking wchar.h usability... yes

checking wchar.h presence... yes

checking for wchar.h... yes

checking for inline... inline

checking for int16_t... yes

checking for int32_t... yes

checking for int64_t... yes

checking for int8_t... yes

checking for size_t... yes

checking for uint16_t... yes

checking for uint32_t... yes

checking for uint64_t... yes

checking for uint8_t... yes

checking for stdlib.h... (cached) yes

checking for GNU libc compatible malloc... yes

checking for memmove... yes

checking for memset... yes

configure: creating ./config.status

config.status: creating src/config.h

warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.

building 'Crypto.Hash._MD2' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/src

x86_64-linux-gnu-gcc -pthread -fwrapv -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python2.7 -c src/MD2.c -o build/temp.linux-x86_64-2.7/src/MD2.o

src/MD2.c:31:20: fatal error: Python.h: No such file or directory

 #include "Python.h"

                    ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-agiU3c/pycrypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-YfY1CT-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-agiU3c/pycrypto
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 295, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 707, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-agiU3c/pycrypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-YfY1CT-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-agiU3c/pycrypto

```

**Comment by benjaoming** [comment] 2015-10-18 17:05
Somehow something wants to compile something (which I think is pycrypto) on your system, but python headers are missing. You should do this firstly:

    sudo apt-get install python-dev

**Comment by EdDixon** [comment] 2015-10-19 12:55
I agree that should solve it checking now, but shouldn't isolate which package or packages are required from dev-python and either include those in the bundle or update the documentation to include this step for other versions of Linux which do not by default have them though? This was tested on a default basic desktop Debian based installation.

**Comment by benjaoming** [comment] 2015-10-19 12:59
Does installing dev headers solve the issue?

We need to get to the bottom of what and why something is being compiled. It's not a matter of diverging from the requirements about being runnable on a blank debian.

**Comment by EdDixon** [comment] 2015-10-19 13:17
It was the lack of python-dev because the pycrypto package is compiled during the installation. sudo apt-get install python-dev just worked around the problem perfectly. @MCGallaspy @benjaoming  We could just add a side note to the docs for now because many version of linux may have this already. Perhaps setting a milestone to see what may be a better way of resolving this for later versions?

**Comment by EdDixon** [comment] 2015-10-19 13:21
This is the pycrypto trace-back from the successful installation

```
  Downloading paramiko-1.15.3-py2.py3-none-any.whl (166kB): 166kB downloaded
Downloading/unpacking pycrypto>=2.1,!=2.4 (from paramiko>=1.7.7->pysftp->django-dbbackup==2.0.5a->ka-lite)
  Downloading pycrypto-2.6.1.tar.gz (446kB): 446kB downloaded
  Running setup.py (path:/tmp/pip-build-P4RE5b/pycrypto/setup.py) egg_info for package pycrypto
    
Downloading/unpacking ecdsa>=0.11 (from paramiko>=1.7.7->pysftp->django-dbbackup==2.0.5a->ka-lite)
  Downloading ecdsa-0.13-py2.py3-none-any.whl (86kB): 86kB downloaded
Installing collected packages: ka-lite, docopt, South, django-js-reverse, slimit, six, django-appconf, python-dateutil, django-dbbackup, sqlitedict, Django, pysftp, paramiko, pycrypto, ecdsa
  Running setup.py install for ka-lite
    
    warning: no previously-included files matching '*' found under directory 'kalite/static'
    warning: no previously-included files matching '*pyc' found under directory 'python-packages'
    warning: no files found matching '*' under directory 'dist-packages'
    changing mode of build/scripts-2.7/kalite from 644 to 755
    changing mode of /usr/local/bin/kalite to 755
  Running setup.py install for docopt
    
  Running setup.py install for slimit
    
    Installing slimit script to /usr/local/bin
  Found existing installation: six 1.8.0
    Not uninstalling six at /usr/lib/python2.7/dist-packages, owned by OS
  Running setup.py install for django-dbbackup
    
  Running setup.py install for sqlitedict
    
  Running setup.py install for pysftp
    
    no previously-included directories found matching 'docs/_build'
  Running setup.py install for pycrypto
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking for __gmpz_init in -lgmp... no
    checking for __gmpz_init in -lmpir... no
    checking whether mpz_powm is declared... no
    checking whether mpz_powm_sec is declared... no
    checking how to run the C preprocessor... gcc -E
    checking for grep that handles long lines and -e... /bin/grep
    checking for egrep... /bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for inttypes.h... (cached) yes
    checking limits.h usability... yes
    checking limits.h presence... yes
    checking for limits.h... yes
    checking stddef.h usability... yes
    checking stddef.h presence... yes
    checking for stddef.h... yes
    checking for stdint.h... (cached) yes
    checking for stdlib.h... (cached) yes
    checking for string.h... (cached) yes
    checking wchar.h usability... yes
    checking wchar.h presence... yes
    checking for wchar.h... yes
    checking for inline... inline
    checking for int16_t... yes
    checking for int32_t... yes
    checking for int64_t... yes
    checking for int8_t... yes
    checking for size_t... yes
    checking for uint16_t... yes
    checking for uint32_t... yes
    checking for uint64_t... yes
    checking for uint8_t... yes
    checking for stdlib.h... (cached) yes
    checking for GNU libc compatible malloc... yes
    checking for memmove... yes
    checking for memset... yes
    configure: creating ./config.status
    config.status: creating src/config.h
    warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
    building 'Crypto.Hash._MD2' extension
    x86_64-linux-gnu-gcc -pthread -fwrapv -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python2.7 -c src/MD2.c -o build/temp.linux-x86_64-2.7/src/MD2.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/MD2.o -o build/lib.linux-x86_64-2.7/Crypto/Hash/_MD2.so
    building 'Crypto.Hash._MD4' extension
    x86_64-linux-gnu-gcc -pthread -fwrapv -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python2.7 -c src/MD4.c -o build/temp.linux-x86_64-2.7/src/MD4.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/MD4.o -o build/lib.linux-x86_64-2.7/Crypto/Hash/_MD4.so
    building 'Crypto.Hash._SHA256' extension
    x86_64-linux-gnu-gcc -pthread -fwrapv -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python2.7 -c src/SHA256.c -o build/temp.linux-x86_64-2.7/src/SHA256.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/SHA256.o -o build/lib.linux-x86_64-2.7/Crypto/Hash/_SHA256.so
    building 'Crypto.Hash._SHA224' extension
    x86_64-linux-gnu-gcc -pthread -fwrapv -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python2.7 -c src/SHA224.c -o build/temp.linux-x86_64-2.7/src/SHA224.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/SHA224.o -o build/lib.linux-x86_64-2.7/Crypto/Hash/_SHA224.so
    building 'Crypto.Hash._SHA384' extension
    x86_64-linux-gnu-gcc -pthread -fwrapv -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python2.7 -c src/SHA384.c -o build/temp.linux-x86_64-2.7/src/SHA384.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/SHA384.o -o build/lib.linux-x86_64-2.7/Crypto/Hash/_SHA384.so
    building 'Crypto.Hash._SHA512' extension
    x86_64-linux-gnu-gcc -pthread -fwrapv -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python2.7 -c src/SHA512.c -o build/temp.linux-x86_64-2.7/src/SHA512.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/SHA512.o -o build/lib.linux-x86_64-2.7/Crypto/Hash/_SHA512.so
    building 'Crypto.Hash._RIPEMD160' extension
    x86_64-linux-gnu-gcc -pthread -fwrapv -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c99 -O3 -fomit-frame-pointer -DPCT_LITTLE_ENDIAN=1 -Isrc/ -I/usr/include/python2.7 -c src/RIPEMD160.c -o build/temp.linux-x86_64-2.7/src/RIPEMD160.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/RIPEMD160.o -o build/lib.linux-x86_64-2.7/Crypto/Hash/_RIPEMD160.so
    building 'Crypto.Cipher._AES' extension
    x86_64-linux-gnu-gcc -pthread -fwrapv -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python2.7 -c src/AES.c -o build/temp.linux-x86_64-2.7/src/AES.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/AES.o -o build/lib.linux-x86_64-2.7/Crypto/Cipher/_AES.so
    building 'Crypto.Cipher._ARC2' extension
    x86_64-linux-gnu-gcc -pthread -fwrapv -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python2.7 -c src/ARC2.c -o build/temp.linux-x86_64-2.7/src/ARC2.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/ARC2.o -o build/lib.linux-x86_64-2.7/Crypto/Cipher/_ARC2.so
    building 'Crypto.Cipher._Blowfish' extension
    x86_64-linux-gnu-gcc -pthread -fwrapv -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python2.7 -c src/Blowfish.c -o build/temp.linux-x86_64-2.7/src/Blowfish.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/Blowfish.o -o build/lib.linux-x86_64-2.7/Crypto/Cipher/_Blowfish.so
    building 'Crypto.Cipher._CAST' extension
    x86_64-linux-gnu-gcc -pthread -fwrapv -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python2.7 -c src/CAST.c -o build/temp.linux-x86_64-2.7/src/CAST.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/CAST.o -o build/lib.linux-x86_64-2.7/Crypto/Cipher/_CAST.so
    building 'Crypto.Cipher._DES' extension
    x86_64-linux-gnu-gcc -pthread -fwrapv -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -Isrc/libtom/ -I/usr/include/python2.7 -c src/DES.c -o build/temp.linux-x86_64-2.7/src/DES.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/DES.o -o build/lib.linux-x86_64-2.7/Crypto/Cipher/_DES.so
    building 'Crypto.Cipher._DES3' extension
    x86_64-linux-gnu-gcc -pthread -fwrapv -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -Isrc/libtom/ -I/usr/include/python2.7 -c src/DES3.c -o build/temp.linux-x86_64-2.7/src/DES3.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/DES3.o -o build/lib.linux-x86_64-2.7/Crypto/Cipher/_DES3.so
    building 'Crypto.Cipher._ARC4' extension
    x86_64-linux-gnu-gcc -pthread -fwrapv -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python2.7 -c src/ARC4.c -o build/temp.linux-x86_64-2.7/src/ARC4.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/ARC4.o -o build/lib.linux-x86_64-2.7/Crypto/Cipher/_ARC4.so
    building 'Crypto.Cipher._XOR' extension
    x86_64-linux-gnu-gcc -pthread -fwrapv -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python2.7 -c src/XOR.c -o build/temp.linux-x86_64-2.7/src/XOR.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/XOR.o -o build/lib.linux-x86_64-2.7/Crypto/Cipher/_XOR.so
    building 'Crypto.Util.strxor' extension
    x86_64-linux-gnu-gcc -pthread -fwrapv -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python2.7 -c src/strxor.c -o build/temp.linux-x86_64-2.7/src/strxor.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/strxor.o -o build/lib.linux-x86_64-2.7/Crypto/Util/strxor.so
    building 'Crypto.Util._counter' extension
    x86_64-linux-gnu-gcc -pthread -fwrapv -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python2.7 -c src/_counter.c -o build/temp.linux-x86_64-2.7/src/_counter.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/_counter.o -o build/lib.linux-x86_64-2.7/Crypto/Util/_counter.so
    
Successfully installed ka-lite docopt South django-js-reverse slimit six django-appconf python-dateutil django-dbbackup sqlitedict Django pysftp paramiko pycrypto ecdsa
Cleaning up...
ed@debian:~$ kalite status
Stopped (1)

```

**Comment by benjaoming** [comment] 2015-10-19 13:23
The question is: Why is pycrypto a requirement?

Could you install pipdeptree and analyze your env?

```
➜  ka-lite git:(cleanup-port-stuff) ✗ pip install pipdeptree
➜  ka-lite git:(cleanup-port-stuff) ✗ pipdeptree
Warning!!! Possible confusing dependencies found:
* ka-lite==0.14.2 -> six [required: ==1.9.0, installed: 1.9.0]
  bpython==0.14.1 -> six [required: >=1.5, installed: 1.9.0]
  django-appconf==1.0.1 -> six [installed: 1.9.0]
* django-compressor==1.4 -> django-appconf [required: >=0.4, installed: 1.0.1]
  ka-lite==0.14.2 -> django-appconf [required: ==1.0.1, installed: 1.0.1]
* slimit==0.8.1 -> ply [required: >=3.4, installed: 3.4]
  ka-lite==0.14.2 -> ply [required: ==3.4, installed: 3.4]
* ka-lite==0.14.2 -> slimit [required: ==0.8.1, installed: 0.8.1]
  django-js-reverse==0.5.0 -> slimit [required: ==0.8.1., installed: 0.8.1]
------------------------------------------------------------------------
wsgiref==0.1.2
argparse==1.2.1
ka-lite==0.14.2
  - django-compressor [required: ==1.4, installed: 1.4]
    - django-appconf [required: >=0.4, installed: 1.0.1]
      - six [installed: 1.9.0]
  - docopt [required: >=0.6, installed: 0.6.2]
  - South [required: ==0.8.4, installed: 0.8.4]
  - django-js-reverse [required: ==0.5.0, installed: 0.5.0]
    - slimit [required: ==0.8.1., installed: 0.8.1]
      - ply [required: >=3.4, installed: 3.4]
    - Django [required: >=1.5, installed: 1.8.3]
  - ply [required: ==3.4, installed: 3.4]
  - slimit [required: ==0.8.1, installed: 0.8.1]
    - ply [required: >=3.4, installed: 3.4]
  - six [required: ==1.9.0, installed: 1.9.0]
  - django-appconf [required: ==1.0.1, installed: 1.0.1]
    - six [installed: 1.9.0]
```

**Comment by EdDixon** [comment] 2015-10-19 13:32
```
ed@debian:~$ pipdeptree
Warning!!! Possible confusing dependencies found:
* cryptography==0.6.1 -> six [required: >=1.4.1, installed: 1.9.0]
  ka-lite==0.15.0 -> six [required: ==1.9.0, installed: 1.9.0]
  python-dateutil==2.4.2 -> six [required: >=1.5, installed: 1.9.0]
  django-dbbackup==2.0.5a -> six [installed: 1.9.0]
  pyOpenSSL==0.14 -> six [required: >=1.5.2, installed: 1.9.0]
  html5lib==0.999 -> six [installed: 1.9.0]
  django-appconf==1.0.1 -> six [installed: 1.9.0]
  python-debian==0.1.27 -> six [installed: 1.9.0]
* ka-lite==0.15.0 -> ply [required: ==3.4, installed: 3.4]
  slimit==0.8.1 -> ply [required: >=3.4, installed: 3.4]
* ka-lite==0.15.0 -> slimit [required: ==0.8.1, installed: 0.8.1]
  django-js-reverse==0.5.0 -> slimit [required: ==0.8.1., installed: 0.8.1]
------------------------------------------------------------------------
argparse==1.2.1
wsgiref==0.1.2
ka-lite==0.15.0
  - docopt [required: >=0.6, installed: 0.6.2]
  - South [required: ==0.8.4, installed: 0.8.4]
  - django-js-reverse [required: ==0.5.0, installed: 0.5.0]
    - Django [required: >=1.5, installed: 1.8.5]
    - slimit [required: ==0.8.1., installed: 0.8.1]
      - ply [required: >=3.4, installed: 3.4]
  - ply [required: ==3.4, installed: 3.4]
  - slimit [required: ==0.8.1, installed: 0.8.1]
    - ply [required: >=3.4, installed: 3.4]
  - six [required: ==1.9.0, installed: 1.9.0]
  - django-appconf [required: ==1.0.1, installed: 1.0.1]
    - six [installed: 1.9.0]
  - python-dateutil [required: ==2.4.2, installed: 2.4.2]
    - six [required: >=1.5, installed: 1.9.0]
  - django-dbbackup [required: ==2.0.5a, installed: 2.0.5a]
    - six [installed: 1.9.0]
    - pysftp [installed: 0.2.8]
      - paramiko [required: >=1.7.7, installed: 1.15.3]
        - pycrypto [required: >=2.1, installed: 2.6.1]
        - ecdsa [required: >=0.11, installed: 0.13]
  - sqlitedict [required: ==1.3.0, installed: 1.3.0]
quodlibet==3.2.2
Pygments==2.0.1
pycurl==7.19.5
Pillow==2.6.1
pycups==1.9.63
pyinotify==0.9.4
numpy==1.8.2
wheel==0.24.0
SOAPpy==0.12.22
  - wstools [installed: 0.4.3]
    - docutils [installed: 0.12]
  - defusedxml [installed: 0.4.1]
uTidylib==0.2
roman==2.0.0
reportbug==6.6.3
python-debian==0.1.27
  - six [installed: 1.9.0]
html5lib==0.999
  - six [installed: 1.9.0]
mutagen==1.25.1
python-apt==0.9.3.12
pyasn1==0.1.7
pygobject==3.14.0
urllib3==1.9.1
requests==2.4.3
colorama==0.3.2
pysmbc==1.0.15.3
chardet==2.3.0
feedparser==5.1.3
ndg-httpsclient==0.3.2
  - pyOpenSSL [installed: 0.14]
    - cryptography [required: >=0.2.1, installed: 0.6.1]
      - cffi [required: >=0.8, installed: 0.8.6]
        - pycparser [installed: 2.10]
      - six [required: >=1.4.1, installed: 1.9.0]
    - six [required: >=1.5.2, installed: 1.9.0]
python-musicbrainz2==0.7.4
python-debianbts==1.11
CDDB==1.4

```

**Comment by benjaoming** [comment] 2015-10-19 13:39
Great, thanks! Now the problem is easy to see!

django-dbbackup has a dependency chain.

This was solved in later versions, which were then broken so we couldn't use the latest version. In the meantime, this is solved:

https://github.com/django-dbbackup/django-dbbackup/issues/120

**Comment by EdDixon** [comment] 2015-10-19 13:40
Awesome!

**Comment by benjaoming** [comment] 2015-10-19 13:42
Since this is a *source* issue, I'm closing and moving here:

https://github.com/learningequality/ka-lite/issues/4634

**Closed by benjaoming** 2015-10-19 13:42 UTC
